### ISSUE TITLE
There are some invalid usernames

### ISSUE THREAD

**Issue by korbert** [brofar/hoss_bots#1]
Hi! I've just banned some of these bots and there are some invalid usernames. Here you have the list:

- hoss00312_12
- hoss_winsss
- hoss_spy
- hoss_hahaha
- hoss00312lliilllillllii
- hoss00312_12

Thanks for your work!

**Comment by w00k-** [comment]
> Hi! I've just banned some of these bots and there are some invalid usernames. Here you have the list:
> 
> * hoss00312_12
> * hoss_winsss
> * hoss_spy
> * hoss_hahaha
> * hoss00312lliilllillllii
> * hoss00312_12
> 
> Thanks for your work!

Likely those accounts were already banned from Twitch, that's why you can't find information on them..

**Comment by brofar** [comment]
Yeah, looks like Twitch is taking action against these bots now, a good number of them are invalid now.

Removed the ones you mentioned :)
